domain_path: C:\Project\CameraLink\PS\LizzieSat\export\LizzieSat\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\peripheral_tests
template: peripheral_tests
